### PR TITLE
Add two new subcommands: `git imerge drop` and `git imerge revert`

### PR DESCRIPTION
**Pull request by mhagger**
Add two new subcommands that start an imerge with the goal to dropping one or more commits from the current branch or creating revert commits that revert one or more existing commits. These operations can both conflict, so they both can benefit from using the incremental merge approach.

### CODE REVIEW

**Comment by waldyrious** [comment]
> These operations can both conflict, so they both can benefit from using the incremental merge approach.

@mhagger I feel that this point is not clear enough in the documentation (README, and possibly help message of those subcommands). Without this clarification, it feels like the two commands introduced here do not really belong with `git-imerge`, and make the tool seemingly break the Unix philosophy.

Do you think you could add that clarification in the relevant ? Otherwise, if you'd give me some pointers about which files to edit and how, I could take a stab at doing this.

**Comment by mhagger** [comment]
> Otherwise, if you'd give me some pointers about which files to edit and how, I could take a stab at doing this.

That would be great! The README is in [`README.rst`](https://github.com/mhagger/git-imerge/blob/master/README.rst) (in reStructuredText format, but it's pretty self-explanatory). The help text is embedded in [`git-imerge`](https://github.com/mhagger/git-imerge/blob/master/git-imerge), for example [here](https://github.com/mhagger/git-imerge/blob/5951fad2945814930374cf0967d3f6b4c050b112/git-imerge#L48-L53), [here](https://github.com/mhagger/git-imerge/blob/5951fad2945814930374cf0967d3f6b4c050b112/git-imerge#L3768-L3771), and [here](https://github.com/mhagger/git-imerge/blob/5951fad2945814930374cf0967d3f6b4c050b112/git-imerge#L3783-L3786).

If you are ambitious, you might consider providing a little bit more explanation of these operations such as discussed [here](https://github.com/mhagger/git-imerge/issues/20#issuecomment-21297035) and [here](https://github.com/mhagger/git-imerge/issues/20#issuecomment-36331551).

**Comment by waldyrious** [comment]
Awesome, I'll give it a try sometime soon :)

**Comment by waldyrious** [comment]
I decided to go ahead with a simple change to the README for now, as the more ambitious approach would likely take quite a bit longer to manifest 😇

**Pull request merged**
